name: CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
      - name: Run a one-line script
        if: success()
        run: .\.github\workflows\putNewVersion.ps1
        shell: powershell
      - name: Commit files
        run: |
          git config --local user.email "arnold.abraham@projanitordevs.com"
          git config --local user.name "ArnoldATProJanitorDevs"
          git commit -m "increases the minor version number" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run build --production
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: finlinUp
          path: dist/financialLineUp
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: finlinUp
          path: dist/financialLineUp
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
