name: CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --production
      - run: npm test
      - name: Run a one-line script
        if: success()
        run: .\.github\workflows\putNewVersion.ps1
        shell: powershell
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: $${{ secrets.FIREBASE_TOKEN}}
